In [1]:
from sklearn import svm
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = pd.read_csv('C:/Users/abhay/Untitled Folder/glass.csv')
y = data['Type']
x = data.drop('Type', 1)

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25)

linear = svm.SVC(kernel='linear')
linear.fit(xtrain, ytrain)
ypred1 = linear.predict(xtest)

#print(linear.support_vectors_)
#print(linear.n_support_)

print("Accuracy Of Linear Kernel: ", accuracy_score(ytest, ypred1))
print("Confusion Matrix: \n", confusion_matrix(ytest, ypred1))
print("Classification report: \n", classification_report(ytest, ypred1))

sigmoid = svm.SVC(kernel='sigmoid')
poly = svm.SVC(kernel='poly')
rbf = svm.SVC(kernel='rbf')

sigmoid.fit(xtrain, ytrain)
poly.fit(xtrain, ytrain)
rbf.fit(xtrain, ytrain)

ypred2 = sigmoid.predict(xtest)
ypred3 = poly.predict(xtest)
ypred4 = rbf.predict(xtest)

print("Accuracy Of Sigmoid Kernel: ", accuracy_score(ytest, ypred2))
print("Accuracy Of Ploy Kernel: ", accuracy_score(ytest, ypred3))
print("Accuracy Of RBF Kernel: ", accuracy_score(ytest, ypred4))

Accuracy Of Linear Kernel:  0.9814814814814815
Confusion Matrix: 
 [[18  0  0  0  0  0]
 [ 0 23  0  0  0  0]
 [ 0  0  2  0  0  0]
 [ 0  0  1  1  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  8]]
Classification report: 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        23
           3       0.67      1.00      0.80         2
           5       1.00      0.50      0.67         2
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         8

    accuracy                           0.98        54
   macro avg       0.94      0.92      0.91        54
weighted avg       0.99      0.98      0.98        54

Accuracy Of Sigmoid Kernel:  0.7037037037037037
Accuracy Of Ploy Kernel:  0.9629629629629629
Accuracy Of RBF Kernel:  0.9259259259259259


C:\Users\abhay\AppData\Local\Temp/ipykernel_9792/2315972515.py:9: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = data.drop('Type', 1)
